-- Copyright 2022 SmartThings
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- DO NOT EDIT: this code is automatically generated by ZCL Advanced Platform generator.

local data_types = require "st.matter.data_types"
local UintABC = require "st.matter.data_types.base_defs.UintABC"

--- @class Global.types.AreaTypeTag: st.matter.data_types.Uint8
--- @alias AreaTypeTag
---
--- @field public byte_length number 1
--- @field public AISLE number 0
--- @field public ATTIC number 1
--- @field public BACK_DOOR number 2
--- @field public BACK_YARD number 3
--- @field public BALCONY number 4
--- @field public BALLROOM number 5
--- @field public BATHROOM number 6
--- @field public BEDROOM number 7
--- @field public BORDER number 8
--- @field public BOXROOM number 9
--- @field public BREAKFAST_ROOM number 10
--- @field public CARPORT number 11
--- @field public CELLAR number 12
--- @field public CLOAKROOM number 13
--- @field public CLOSET number 14
--- @field public CONSERVATORY number 15
--- @field public CORRIDOR number 16
--- @field public CRAFT_ROOM number 17
--- @field public CUPBOARD number 18
--- @field public DECK number 19
--- @field public DEN number 20
--- @field public DINING number 21
--- @field public DRAWING_ROOM number 22
--- @field public DRESSING_ROOM number 23
--- @field public DRIVEWAY number 24
--- @field public ELEVATOR number 25
--- @field public ENSUITE number 26
--- @field public ENTRANCE number 27
--- @field public ENTRYWAY number 28
--- @field public FAMILY_ROOM number 29
--- @field public FOYER number 30
--- @field public FRONT_DOOR number 31
--- @field public FRONT_YARD number 32
--- @field public GAME_ROOM number 33
--- @field public GARAGE number 34
--- @field public GARAGE_DOOR number 35
--- @field public GARDEN number 36
--- @field public GARDEN_DOOR number 37
--- @field public GUEST_BATHROOM number 38
--- @field public GUEST_BEDROOM number 39
--- @field public GUEST_RESTROOM number 40
--- @field public GUEST_ROOM number 41
--- @field public GYM number 42
--- @field public HALLWAY number 43
--- @field public HEARTH_ROOM number 44
--- @field public KIDS_ROOM number 45
--- @field public KIDS_BEDROOM number 46
--- @field public KITCHEN number 47
--- @field public LARDER number 48
--- @field public LAUNDRY_ROOM number 49
--- @field public LAWN number 50
--- @field public LIBRARY number 51
--- @field public LIVING_ROOM number 52
--- @field public LOUNGE number 53
--- @field public MEDIA_TV_ROOM number 54
--- @field public MUD_ROOM number 55
--- @field public MUSIC_ROOM number 56
--- @field public NURSERY number 57
--- @field public OFFICE number 58
--- @field public OUTDOOR_KITCHEN number 59
--- @field public OUTSIDE number 60
--- @field public PANTRY number 61
--- @field public PARKING_LOT number 62
--- @field public PARLOR number 63
--- @field public PATIO number 64
--- @field public PLAY_ROOM number 65
--- @field public POOL_ROOM number 66
--- @field public PORCH number 67
--- @field public PRIMARY_BATHROOM number 68
--- @field public PRIMARY_BEDROOM number 69
--- @field public RAMP number 70
--- @field public RECEPTION_ROOM number 71
--- @field public RECREATION_ROOM number 72
--- @field public RESTROOM number 73
--- @field public ROOF number 74
--- @field public SAUNA number 75
--- @field public SCULLERY number 76
--- @field public SEWING_ROOM number 77
--- @field public SHED number 78
--- @field public SIDE_DOOR number 79
--- @field public SIDE_YARD number 80
--- @field public SITTING_ROOM number 81
--- @field public SNUG number 82
--- @field public SPA number 83
--- @field public STAIRCASE number 84
--- @field public STEAM_ROOM number 85
--- @field public STORAGE_ROOM number 86
--- @field public STUDIO number 87
--- @field public STUDY number 88
--- @field public SUN_ROOM number 89
--- @field public SWIMMING_POOL number 90
--- @field public TERRACE number 91
--- @field public UTILITY_ROOM number 92
--- @field public WARD number 93
--- @field public WORKSHOP number 94

local AreaTypeTag = {}
local new_mt = UintABC.new_mt({NAME = "AreaTypeTag", ID = data_types.name_to_id_map["Uint8"]}, 1)
new_mt.__index.pretty_print = function(self)
  local name_lookup = {
    [self.AISLE] = "AISLE",
    [self.ATTIC] = "ATTIC",
    [self.BACK_DOOR] = "BACK_DOOR",
    [self.BACK_YARD] = "BACK_YARD",
    [self.BALCONY] = "BALCONY",
    [self.BALLROOM] = "BALLROOM",
    [self.BATHROOM] = "BATHROOM",
    [self.BEDROOM] = "BEDROOM",
    [self.BORDER] = "BORDER",
    [self.BOXROOM] = "BOXROOM",
    [self.BREAKFAST_ROOM] = "BREAKFAST_ROOM",
    [self.CARPORT] = "CARPORT",
    [self.CELLAR] = "CELLAR",
    [self.CLOAKROOM] = "CLOAKROOM",
    [self.CLOSET] = "CLOSET",
    [self.CONSERVATORY] = "CONSERVATORY",
    [self.CORRIDOR] = "CORRIDOR",
    [self.CRAFT_ROOM] = "CRAFT_ROOM",
    [self.CUPBOARD] = "CUPBOARD",
    [self.DECK] = "DECK",
    [self.DEN] = "DEN",
    [self.DINING] = "DINING",
    [self.DRAWING_ROOM] = "DRAWING_ROOM",
    [self.DRESSING_ROOM] = "DRESSING_ROOM",
    [self.DRIVEWAY] = "DRIVEWAY",
    [self.ELEVATOR] = "ELEVATOR",
    [self.ENSUITE] = "ENSUITE",
    [self.ENTRANCE] = "ENTRANCE",
    [self.ENTRYWAY] = "ENTRYWAY",
    [self.FAMILY_ROOM] = "FAMILY_ROOM",
    [self.FOYER] = "FOYER",
    [self.FRONT_DOOR] = "FRONT_DOOR",
    [self.FRONT_YARD] = "FRONT_YARD",
    [self.GAME_ROOM] = "GAME_ROOM",
    [self.GARAGE] = "GARAGE",
    [self.GARAGE_DOOR] = "GARAGE_DOOR",
    [self.GARDEN] = "GARDEN",
    [self.GARDEN_DOOR] = "GARDEN_DOOR",
    [self.GUEST_BATHROOM] = "GUEST_BATHROOM",
    [self.GUEST_BEDROOM] = "GUEST_BEDROOM",
    [self.GUEST_RESTROOM] = "GUEST_RESTROOM",
    [self.GUEST_ROOM] = "GUEST_ROOM",
    [self.GYM] = "GYM",
    [self.HALLWAY] = "HALLWAY",
    [self.HEARTH_ROOM] = "HEARTH_ROOM",
    [self.KIDS_ROOM] = "KIDS_ROOM",
    [self.KIDS_BEDROOM] = "KIDS_BEDROOM",
    [self.KITCHEN] = "KITCHEN",
    [self.LARDER] = "LARDER",
    [self.LAUNDRY_ROOM] = "LAUNDRY_ROOM",
    [self.LAWN] = "LAWN",
    [self.LIBRARY] = "LIBRARY",
    [self.LIVING_ROOM] = "LIVING_ROOM",
    [self.LOUNGE] = "LOUNGE",
    [self.MEDIA_TV_ROOM] = "MEDIA_TV_ROOM",
    [self.MUD_ROOM] = "MUD_ROOM",
    [self.MUSIC_ROOM] = "MUSIC_ROOM",
    [self.NURSERY] = "NURSERY",
    [self.OFFICE] = "OFFICE",
    [self.OUTDOOR_KITCHEN] = "OUTDOOR_KITCHEN",
    [self.OUTSIDE] = "OUTSIDE",
    [self.PANTRY] = "PANTRY",
    [self.PARKING_LOT] = "PARKING_LOT",
    [self.PARLOR] = "PARLOR",
    [self.PATIO] = "PATIO",
    [self.PLAY_ROOM] = "PLAY_ROOM",
    [self.POOL_ROOM] = "POOL_ROOM",
    [self.PORCH] = "PORCH",
    [self.PRIMARY_BATHROOM] = "PRIMARY_BATHROOM",
    [self.PRIMARY_BEDROOM] = "PRIMARY_BEDROOM",
    [self.RAMP] = "RAMP",
    [self.RECEPTION_ROOM] = "RECEPTION_ROOM",
    [self.RECREATION_ROOM] = "RECREATION_ROOM",
    [self.RESTROOM] = "RESTROOM",
    [self.ROOF] = "ROOF",
    [self.SAUNA] = "SAUNA",
    [self.SCULLERY] = "SCULLERY",
    [self.SEWING_ROOM] = "SEWING_ROOM",
    [self.SHED] = "SHED",
    [self.SIDE_DOOR] = "SIDE_DOOR",
    [self.SIDE_YARD] = "SIDE_YARD",
    [self.SITTING_ROOM] = "SITTING_ROOM",
    [self.SNUG] = "SNUG",
    [self.SPA] = "SPA",
    [self.STAIRCASE] = "STAIRCASE",
    [self.STEAM_ROOM] = "STEAM_ROOM",
    [self.STORAGE_ROOM] = "STORAGE_ROOM",
    [self.STUDIO] = "STUDIO",
    [self.STUDY] = "STUDY",
    [self.SUN_ROOM] = "SUN_ROOM",
    [self.SWIMMING_POOL] = "SWIMMING_POOL",
    [self.TERRACE] = "TERRACE",
    [self.UTILITY_ROOM] = "UTILITY_ROOM",
    [self.WARD] = "WARD",
    [self.WORKSHOP] = "WORKSHOP",
  }
  return string.format("%s: %s", self.field_name or self.NAME, name_lookup[self.value] or string.format("%d", self.value))
end
new_mt.__tostring = new_mt.__index.pretty_print

new_mt.__index.AISLE  = 0x00
new_mt.__index.ATTIC  = 0x01
new_mt.__index.BACK_DOOR  = 0x02
new_mt.__index.BACK_YARD  = 0x03
new_mt.__index.BALCONY  = 0x04
new_mt.__index.BALLROOM  = 0x05
new_mt.__index.BATHROOM  = 0x06
new_mt.__index.BEDROOM  = 0x07
new_mt.__index.BORDER  = 0x08
new_mt.__index.BOXROOM  = 0x09
new_mt.__index.BREAKFAST_ROOM  = 0x0A
new_mt.__index.CARPORT  = 0x0B
new_mt.__index.CELLAR  = 0x0C
new_mt.__index.CLOAKROOM  = 0x0D
new_mt.__index.CLOSET  = 0x0E
new_mt.__index.CONSERVATORY  = 0x0F
new_mt.__index.CORRIDOR  = 0x10
new_mt.__index.CRAFT_ROOM  = 0x11
new_mt.__index.CUPBOARD  = 0x12
new_mt.__index.DECK  = 0x13
new_mt.__index.DEN  = 0x14
new_mt.__index.DINING  = 0x15
new_mt.__index.DRAWING_ROOM  = 0x16
new_mt.__index.DRESSING_ROOM  = 0x17
new_mt.__index.DRIVEWAY  = 0x18
new_mt.__index.ELEVATOR  = 0x19
new_mt.__index.ENSUITE  = 0x1A
new_mt.__index.ENTRANCE  = 0x1B
new_mt.__index.ENTRYWAY  = 0x1C
new_mt.__index.FAMILY_ROOM  = 0x1D
new_mt.__index.FOYER  = 0x1E
new_mt.__index.FRONT_DOOR  = 0x1F
new_mt.__index.FRONT_YARD  = 0x20
new_mt.__index.GAME_ROOM  = 0x21
new_mt.__index.GARAGE  = 0x22
new_mt.__index.GARAGE_DOOR  = 0x23
new_mt.__index.GARDEN  = 0x24
new_mt.__index.GARDEN_DOOR  = 0x25
new_mt.__index.GUEST_BATHROOM  = 0x26
new_mt.__index.GUEST_BEDROOM  = 0x27
new_mt.__index.GUEST_RESTROOM  = 0x28
new_mt.__index.GUEST_ROOM  = 0x29
new_mt.__index.GYM  = 0x2A
new_mt.__index.HALLWAY  = 0x2B
new_mt.__index.HEARTH_ROOM  = 0x2C
new_mt.__index.KIDS_ROOM  = 0x2D
new_mt.__index.KIDS_BEDROOM  = 0x2E
new_mt.__index.KITCHEN  = 0x2F
new_mt.__index.LARDER  = 0x30
new_mt.__index.LAUNDRY_ROOM  = 0x31
new_mt.__index.LAWN  = 0x32
new_mt.__index.LIBRARY  = 0x33
new_mt.__index.LIVING_ROOM  = 0x34
new_mt.__index.LOUNGE  = 0x35
new_mt.__index.MEDIA_TV_ROOM  = 0x36
new_mt.__index.MUD_ROOM  = 0x37
new_mt.__index.MUSIC_ROOM  = 0x38
new_mt.__index.NURSERY  = 0x39
new_mt.__index.OFFICE  = 0x3A
new_mt.__index.OUTDOOR_KITCHEN  = 0x3B
new_mt.__index.OUTSIDE  = 0x3C
new_mt.__index.PANTRY  = 0x3D
new_mt.__index.PARKING_LOT  = 0x3E
new_mt.__index.PARLOR  = 0x3F
new_mt.__index.PATIO  = 0x40
new_mt.__index.PLAY_ROOM  = 0x41
new_mt.__index.POOL_ROOM  = 0x42
new_mt.__index.PORCH  = 0x43
new_mt.__index.PRIMARY_BATHROOM  = 0x44
new_mt.__index.PRIMARY_BEDROOM  = 0x45
new_mt.__index.RAMP  = 0x46
new_mt.__index.RECEPTION_ROOM  = 0x47
new_mt.__index.RECREATION_ROOM  = 0x48
new_mt.__index.RESTROOM  = 0x49
new_mt.__index.ROOF  = 0x4A
new_mt.__index.SAUNA  = 0x4B
new_mt.__index.SCULLERY  = 0x4C
new_mt.__index.SEWING_ROOM  = 0x4D
new_mt.__index.SHED  = 0x4E
new_mt.__index.SIDE_DOOR  = 0x4F
new_mt.__index.SIDE_YARD  = 0x50
new_mt.__index.SITTING_ROOM  = 0x51
new_mt.__index.SNUG  = 0x52
new_mt.__index.SPA  = 0x53
new_mt.__index.STAIRCASE  = 0x54
new_mt.__index.STEAM_ROOM  = 0x55
new_mt.__index.STORAGE_ROOM  = 0x56
new_mt.__index.STUDIO  = 0x57
new_mt.__index.STUDY  = 0x58
new_mt.__index.SUN_ROOM  = 0x59
new_mt.__index.SWIMMING_POOL  = 0x5A
new_mt.__index.TERRACE  = 0x5B
new_mt.__index.UTILITY_ROOM  = 0x5C
new_mt.__index.WARD  = 0x5D
new_mt.__index.WORKSHOP  = 0x5E

AreaTypeTag.AISLE  = 0x00
AreaTypeTag.ATTIC  = 0x01
AreaTypeTag.BACK_DOOR  = 0x02
AreaTypeTag.BACK_YARD  = 0x03
AreaTypeTag.BALCONY  = 0x04
AreaTypeTag.BALLROOM  = 0x05
AreaTypeTag.BATHROOM  = 0x06
AreaTypeTag.BEDROOM  = 0x07
AreaTypeTag.BORDER  = 0x08
AreaTypeTag.BOXROOM  = 0x09
AreaTypeTag.BREAKFAST_ROOM  = 0x0A
AreaTypeTag.CARPORT  = 0x0B
AreaTypeTag.CELLAR  = 0x0C
AreaTypeTag.CLOAKROOM  = 0x0D
AreaTypeTag.CLOSET  = 0x0E
AreaTypeTag.CONSERVATORY  = 0x0F
AreaTypeTag.CORRIDOR  = 0x10
AreaTypeTag.CRAFT_ROOM  = 0x11
AreaTypeTag.CUPBOARD  = 0x12
AreaTypeTag.DECK  = 0x13
AreaTypeTag.DEN  = 0x14
AreaTypeTag.DINING  = 0x15
AreaTypeTag.DRAWING_ROOM  = 0x16
AreaTypeTag.DRESSING_ROOM  = 0x17
AreaTypeTag.DRIVEWAY  = 0x18
AreaTypeTag.ELEVATOR  = 0x19
AreaTypeTag.ENSUITE  = 0x1A
AreaTypeTag.ENTRANCE  = 0x1B
AreaTypeTag.ENTRYWAY  = 0x1C
AreaTypeTag.FAMILY_ROOM  = 0x1D
AreaTypeTag.FOYER  = 0x1E
AreaTypeTag.FRONT_DOOR  = 0x1F
AreaTypeTag.FRONT_YARD  = 0x20
AreaTypeTag.GAME_ROOM  = 0x21
AreaTypeTag.GARAGE  = 0x22
AreaTypeTag.GARAGE_DOOR  = 0x23
AreaTypeTag.GARDEN  = 0x24
AreaTypeTag.GARDEN_DOOR  = 0x25
AreaTypeTag.GUEST_BATHROOM  = 0x26
AreaTypeTag.GUEST_BEDROOM  = 0x27
AreaTypeTag.GUEST_RESTROOM  = 0x28
AreaTypeTag.GUEST_ROOM  = 0x29
AreaTypeTag.GYM  = 0x2A
AreaTypeTag.HALLWAY  = 0x2B
AreaTypeTag.HEARTH_ROOM  = 0x2C
AreaTypeTag.KIDS_ROOM  = 0x2D
AreaTypeTag.KIDS_BEDROOM  = 0x2E
AreaTypeTag.KITCHEN  = 0x2F
AreaTypeTag.LARDER  = 0x30
AreaTypeTag.LAUNDRY_ROOM  = 0x31
AreaTypeTag.LAWN  = 0x32
AreaTypeTag.LIBRARY  = 0x33
AreaTypeTag.LIVING_ROOM  = 0x34
AreaTypeTag.LOUNGE  = 0x35
AreaTypeTag.MEDIA_TV_ROOM  = 0x36
AreaTypeTag.MUD_ROOM  = 0x37
AreaTypeTag.MUSIC_ROOM  = 0x38
AreaTypeTag.NURSERY  = 0x39
AreaTypeTag.OFFICE  = 0x3A
AreaTypeTag.OUTDOOR_KITCHEN  = 0x3B
AreaTypeTag.OUTSIDE  = 0x3C
AreaTypeTag.PANTRY  = 0x3D
AreaTypeTag.PARKING_LOT  = 0x3E
AreaTypeTag.PARLOR  = 0x3F
AreaTypeTag.PATIO  = 0x40
AreaTypeTag.PLAY_ROOM  = 0x41
AreaTypeTag.POOL_ROOM  = 0x42
AreaTypeTag.PORCH  = 0x43
AreaTypeTag.PRIMARY_BATHROOM  = 0x44
AreaTypeTag.PRIMARY_BEDROOM  = 0x45
AreaTypeTag.RAMP  = 0x46
AreaTypeTag.RECEPTION_ROOM  = 0x47
AreaTypeTag.RECREATION_ROOM  = 0x48
AreaTypeTag.RESTROOM  = 0x49
AreaTypeTag.ROOF  = 0x4A
AreaTypeTag.SAUNA  = 0x4B
AreaTypeTag.SCULLERY  = 0x4C
AreaTypeTag.SEWING_ROOM  = 0x4D
AreaTypeTag.SHED  = 0x4E
AreaTypeTag.SIDE_DOOR  = 0x4F
AreaTypeTag.SIDE_YARD  = 0x50
AreaTypeTag.SITTING_ROOM  = 0x51
AreaTypeTag.SNUG  = 0x52
AreaTypeTag.SPA  = 0x53
AreaTypeTag.STAIRCASE  = 0x54
AreaTypeTag.STEAM_ROOM  = 0x55
AreaTypeTag.STORAGE_ROOM  = 0x56
AreaTypeTag.STUDIO  = 0x57
AreaTypeTag.STUDY  = 0x58
AreaTypeTag.SUN_ROOM  = 0x59
AreaTypeTag.SWIMMING_POOL  = 0x5A
AreaTypeTag.TERRACE  = 0x5B
AreaTypeTag.UTILITY_ROOM  = 0x5C
AreaTypeTag.WARD  = 0x5D
AreaTypeTag.WORKSHOP  = 0x5E

AreaTypeTag.augment_type = function(cls, val)
  setmetatable(val, new_mt)
end

setmetatable(AreaTypeTag, new_mt)

return AreaTypeTag

