-- Copyright 2022 SmartThings
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- DO NOT EDIT: this code is automatically generated by ZCL Advanced Platform generator.

local data_types = require "st.matter.data_types"
local UintABC = require "st.matter.data_types.base_defs.UintABC"

--- @class Global.types.LandmarkTag: st.matter.data_types.Uint8
--- @alias LandmarkTag
---
--- @field public byte_length number 1
--- @field public AIR_CONDITIONER number 0
--- @field public AIR_PURIFIER number 1
--- @field public BACK_DOOR number 2
--- @field public BAR_STOOL number 3
--- @field public BATH_MAT number 4
--- @field public BATHTUB number 5
--- @field public BED number 6
--- @field public BOOKSHELF number 7
--- @field public CHAIR number 8
--- @field public CHRISTMAS_TREE number 9
--- @field public COAT_RACK number 10
--- @field public COFFEE_TABLE number 11
--- @field public COOKING_RANGE number 12
--- @field public COUCH number 13
--- @field public COUNTERTOP number 14
--- @field public CRADLE number 15
--- @field public CRIB number 16
--- @field public DESK number 17
--- @field public DINING_TABLE number 18
--- @field public DISHWASHER number 19
--- @field public DOOR number 20
--- @field public DRESSER number 21
--- @field public LAUNDRY_DRYER number 22
--- @field public FAN number 23
--- @field public FIREPLACE number 24
--- @field public FREEZER number 25
--- @field public FRONT_DOOR number 26
--- @field public HIGH_CHAIR number 27
--- @field public KITCHEN_ISLAND number 28
--- @field public LAMP number 29
--- @field public LITTER_BOX number 30
--- @field public MIRROR number 31
--- @field public NIGHTSTAND number 32
--- @field public OVEN number 33
--- @field public PET_BED number 34
--- @field public PET_BOWL number 35
--- @field public PET_CRATE number 36
--- @field public REFRIGERATOR number 37
--- @field public SCRATCHING_POST number 38
--- @field public SHOE_RACK number 39
--- @field public SHOWER number 40
--- @field public SIDE_DOOR number 41
--- @field public SINK number 42
--- @field public SOFA number 43
--- @field public STOVE number 44
--- @field public TABLE number 45
--- @field public TOILET number 46
--- @field public TRASH_CAN number 47
--- @field public LAUNDRY_WASHER number 48
--- @field public WINDOW number 49
--- @field public WINE_COOLER number 50

local LandmarkTag = {}
local new_mt = UintABC.new_mt({NAME = "LandmarkTag", ID = data_types.name_to_id_map["Uint8"]}, 1)
new_mt.__index.pretty_print = function(self)
  local name_lookup = {
    [self.AIR_CONDITIONER] = "AIR_CONDITIONER",
    [self.AIR_PURIFIER] = "AIR_PURIFIER",
    [self.BACK_DOOR] = "BACK_DOOR",
    [self.BAR_STOOL] = "BAR_STOOL",
    [self.BATH_MAT] = "BATH_MAT",
    [self.BATHTUB] = "BATHTUB",
    [self.BED] = "BED",
    [self.BOOKSHELF] = "BOOKSHELF",
    [self.CHAIR] = "CHAIR",
    [self.CHRISTMAS_TREE] = "CHRISTMAS_TREE",
    [self.COAT_RACK] = "COAT_RACK",
    [self.COFFEE_TABLE] = "COFFEE_TABLE",
    [self.COOKING_RANGE] = "COOKING_RANGE",
    [self.COUCH] = "COUCH",
    [self.COUNTERTOP] = "COUNTERTOP",
    [self.CRADLE] = "CRADLE",
    [self.CRIB] = "CRIB",
    [self.DESK] = "DESK",
    [self.DINING_TABLE] = "DINING_TABLE",
    [self.DISHWASHER] = "DISHWASHER",
    [self.DOOR] = "DOOR",
    [self.DRESSER] = "DRESSER",
    [self.LAUNDRY_DRYER] = "LAUNDRY_DRYER",
    [self.FAN] = "FAN",
    [self.FIREPLACE] = "FIREPLACE",
    [self.FREEZER] = "FREEZER",
    [self.FRONT_DOOR] = "FRONT_DOOR",
    [self.HIGH_CHAIR] = "HIGH_CHAIR",
    [self.KITCHEN_ISLAND] = "KITCHEN_ISLAND",
    [self.LAMP] = "LAMP",
    [self.LITTER_BOX] = "LITTER_BOX",
    [self.MIRROR] = "MIRROR",
    [self.NIGHTSTAND] = "NIGHTSTAND",
    [self.OVEN] = "OVEN",
    [self.PET_BED] = "PET_BED",
    [self.PET_BOWL] = "PET_BOWL",
    [self.PET_CRATE] = "PET_CRATE",
    [self.REFRIGERATOR] = "REFRIGERATOR",
    [self.SCRATCHING_POST] = "SCRATCHING_POST",
    [self.SHOE_RACK] = "SHOE_RACK",
    [self.SHOWER] = "SHOWER",
    [self.SIDE_DOOR] = "SIDE_DOOR",
    [self.SINK] = "SINK",
    [self.SOFA] = "SOFA",
    [self.STOVE] = "STOVE",
    [self.TABLE] = "TABLE",
    [self.TOILET] = "TOILET",
    [self.TRASH_CAN] = "TRASH_CAN",
    [self.LAUNDRY_WASHER] = "LAUNDRY_WASHER",
    [self.WINDOW] = "WINDOW",
    [self.WINE_COOLER] = "WINE_COOLER",
  }
  return string.format("%s: %s", self.field_name or self.NAME, name_lookup[self.value] or string.format("%d", self.value))
end
new_mt.__tostring = new_mt.__index.pretty_print

new_mt.__index.AIR_CONDITIONER  = 0x00
new_mt.__index.AIR_PURIFIER  = 0x01
new_mt.__index.BACK_DOOR  = 0x02
new_mt.__index.BAR_STOOL  = 0x03
new_mt.__index.BATH_MAT  = 0x04
new_mt.__index.BATHTUB  = 0x05
new_mt.__index.BED  = 0x06
new_mt.__index.BOOKSHELF  = 0x07
new_mt.__index.CHAIR  = 0x08
new_mt.__index.CHRISTMAS_TREE  = 0x09
new_mt.__index.COAT_RACK  = 0x0A
new_mt.__index.COFFEE_TABLE  = 0x0B
new_mt.__index.COOKING_RANGE  = 0x0C
new_mt.__index.COUCH  = 0x0D
new_mt.__index.COUNTERTOP  = 0x0E
new_mt.__index.CRADLE  = 0x0F
new_mt.__index.CRIB  = 0x10
new_mt.__index.DESK  = 0x11
new_mt.__index.DINING_TABLE  = 0x12
new_mt.__index.DISHWASHER  = 0x13
new_mt.__index.DOOR  = 0x14
new_mt.__index.DRESSER  = 0x15
new_mt.__index.LAUNDRY_DRYER  = 0x16
new_mt.__index.FAN  = 0x17
new_mt.__index.FIREPLACE  = 0x18
new_mt.__index.FREEZER  = 0x19
new_mt.__index.FRONT_DOOR  = 0x1A
new_mt.__index.HIGH_CHAIR  = 0x1B
new_mt.__index.KITCHEN_ISLAND  = 0x1C
new_mt.__index.LAMP  = 0x1D
new_mt.__index.LITTER_BOX  = 0x1E
new_mt.__index.MIRROR  = 0x1F
new_mt.__index.NIGHTSTAND  = 0x20
new_mt.__index.OVEN  = 0x21
new_mt.__index.PET_BED  = 0x22
new_mt.__index.PET_BOWL  = 0x23
new_mt.__index.PET_CRATE  = 0x24
new_mt.__index.REFRIGERATOR  = 0x25
new_mt.__index.SCRATCHING_POST  = 0x26
new_mt.__index.SHOE_RACK  = 0x27
new_mt.__index.SHOWER  = 0x28
new_mt.__index.SIDE_DOOR  = 0x29
new_mt.__index.SINK  = 0x2A
new_mt.__index.SOFA  = 0x2B
new_mt.__index.STOVE  = 0x2C
new_mt.__index.TABLE  = 0x2D
new_mt.__index.TOILET  = 0x2E
new_mt.__index.TRASH_CAN  = 0x2F
new_mt.__index.LAUNDRY_WASHER  = 0x30
new_mt.__index.WINDOW  = 0x31
new_mt.__index.WINE_COOLER  = 0x32

LandmarkTag.AIR_CONDITIONER  = 0x00
LandmarkTag.AIR_PURIFIER  = 0x01
LandmarkTag.BACK_DOOR  = 0x02
LandmarkTag.BAR_STOOL  = 0x03
LandmarkTag.BATH_MAT  = 0x04
LandmarkTag.BATHTUB  = 0x05
LandmarkTag.BED  = 0x06
LandmarkTag.BOOKSHELF  = 0x07
LandmarkTag.CHAIR  = 0x08
LandmarkTag.CHRISTMAS_TREE  = 0x09
LandmarkTag.COAT_RACK  = 0x0A
LandmarkTag.COFFEE_TABLE  = 0x0B
LandmarkTag.COOKING_RANGE  = 0x0C
LandmarkTag.COUCH  = 0x0D
LandmarkTag.COUNTERTOP  = 0x0E
LandmarkTag.CRADLE  = 0x0F
LandmarkTag.CRIB  = 0x10
LandmarkTag.DESK  = 0x11
LandmarkTag.DINING_TABLE  = 0x12
LandmarkTag.DISHWASHER  = 0x13
LandmarkTag.DOOR  = 0x14
LandmarkTag.DRESSER  = 0x15
LandmarkTag.LAUNDRY_DRYER  = 0x16
LandmarkTag.FAN  = 0x17
LandmarkTag.FIREPLACE  = 0x18
LandmarkTag.FREEZER  = 0x19
LandmarkTag.FRONT_DOOR  = 0x1A
LandmarkTag.HIGH_CHAIR  = 0x1B
LandmarkTag.KITCHEN_ISLAND  = 0x1C
LandmarkTag.LAMP  = 0x1D
LandmarkTag.LITTER_BOX  = 0x1E
LandmarkTag.MIRROR  = 0x1F
LandmarkTag.NIGHTSTAND  = 0x20
LandmarkTag.OVEN  = 0x21
LandmarkTag.PET_BED  = 0x22
LandmarkTag.PET_BOWL  = 0x23
LandmarkTag.PET_CRATE  = 0x24
LandmarkTag.REFRIGERATOR  = 0x25
LandmarkTag.SCRATCHING_POST  = 0x26
LandmarkTag.SHOE_RACK  = 0x27
LandmarkTag.SHOWER  = 0x28
LandmarkTag.SIDE_DOOR  = 0x29
LandmarkTag.SINK  = 0x2A
LandmarkTag.SOFA  = 0x2B
LandmarkTag.STOVE  = 0x2C
LandmarkTag.TABLE  = 0x2D
LandmarkTag.TOILET  = 0x2E
LandmarkTag.TRASH_CAN  = 0x2F
LandmarkTag.LAUNDRY_WASHER  = 0x30
LandmarkTag.WINDOW  = 0x31
LandmarkTag.WINE_COOLER  = 0x32

LandmarkTag.augment_type = function(cls, val)
  setmetatable(val, new_mt)
end

setmetatable(LandmarkTag, new_mt)

return LandmarkTag

