-- Copyright 2022 SmartThings, Inc.
-- Licensed under the Apache License, Version 2.0


-- DO NOT EDIT: this code is automatically generated by ZCL Advanced Platform generator.

local event_mt = {}
event_mt.__event_cache = {}
event_mt.__index = function(self, key)
  if event_mt.__event_cache[key] == nil then
    local req_loc = string.format("embedded_clusters.PressureMeasurement.server.events.%s", key)
    local raw_def = require(req_loc)
    local cluster = rawget(self, "_cluster")
    raw_def:set_parent_cluster(cluster)
    event_mt.__event_cache[key] = raw_def
  end
  return event_mt.__event_cache[key]
end

--- @class PressureMeasurementEvents
---
local PressureMeasurementEvents = {}

function PressureMeasurementEvents:set_parent_cluster(cluster)
  self._cluster = cluster
  return self
end

setmetatable(PressureMeasurementEvents, event_mt)

return PressureMeasurementEvents
