-- Copyright 2022 SmartThings, Inc.
-- Licensed under the Apache License, Version 2.0


-- DO NOT EDIT: this code is automatically generated by ZCL Advanced Platform generator.

local command_mt = {}
command_mt.__command_cache = {}
command_mt.__index = function(self, key)
  if command_mt.__command_cache[key] == nil then
    local req_loc = string.format("embedded_clusters.PressureMeasurement.server.commands.%s", key)
    local raw_def = require(req_loc)
    local cluster = rawget(self, "_cluster")
    command_mt.__command_cache[key] = raw_def:set_parent_cluster(cluster)
  end
  return command_mt.__command_cache[key]
end

--- @class PressureMeasurementServerCommands
---
local PressureMeasurementServerCommands = {}

function PressureMeasurementServerCommands:set_parent_cluster(cluster)
  self._cluster = cluster
  return self
end

setmetatable(PressureMeasurementServerCommands, command_mt)

return PressureMeasurementServerCommands
