-- Copyright 2022 SmartThings
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- DO NOT EDIT: this code is automatically generated by ZCL Advanced Platform generator.

local cluster_base = require "st.matter.cluster_base"
local PressureMeasurementServerAttributes = require "PressureMeasurement.server.attributes"
local PressureMeasurementServerCommands = require "PressureMeasurement.server.commands"
local PressureMeasurementTypes = require "PressureMeasurement.types"

--- @class PressureMeasurement
--- @alias PressureMeasurement
---
--- @field public ID number 0x0403 the ID of this cluster
--- @field public NAME string "PressureMeasurement" the name of this cluster
--- @field public attributes PressureMeasurementServerAttributes | PressureMeasurementClientAttributes
--- @field public commands PressureMeasurementServerCommands | PressureMeasurementClientCommands
--- @field public types PressureMeasurementTypes

local PressureMeasurement = {}

PressureMeasurement.ID = 0x0403
PressureMeasurement.NAME = "PressureMeasurement"
PressureMeasurement.server = {}
PressureMeasurement.client = {}
PressureMeasurement.server.attributes = PressureMeasurementServerAttributes:set_parent_cluster(PressureMeasurement)
PressureMeasurement.server.commands = PressureMeasurementServerCommands:set_parent_cluster(PressureMeasurement)
PressureMeasurement.types = PressureMeasurementTypes


--- Find an attribute by id
---
--- @param attr_id number
function PressureMeasurement:get_attribute_by_id(attr_id)
  local attr_id_map = {
    [0x0000] = "MeasuredValue",
    [0x0001] = "MinMeasuredValue",
    [0x0002] = "MaxMeasuredValue",
    [0x0003] = "Tolerance",
    [0x0010] = "ScaledValue",
    [0x0011] = "MinScaledValue",
    [0x0012] = "MaxScaledValue",
    [0x0013] = "ScaledTolerance",
    [0x0014] = "Scale",
    [0xFFF9] = "AcceptedCommandList",
    [0xFFFA] = "EventList",
    [0xFFFB] = "AttributeList",
  }
  local attr_name = attr_id_map[attr_id]
  if attr_name ~= nil then
    return self.attributes[attr_name]
  end
  return nil
end

--- Find a server command by id
---
--- @param command_id number
function PressureMeasurement:get_server_command_by_id(command_id)
  local server_id_map = {
  }
  if server_id_map[command_id] ~= nil then
    return self.server.commands[server_id_map[command_id]]
  end
  return nil
end


-- Attribute Mapping
PressureMeasurement.attribute_direction_map = {
  ["MeasuredValue"] = "server",
  ["MinMeasuredValue"] = "server",
  ["MaxMeasuredValue"] = "server",
  ["Tolerance"] = "server",
  ["ScaledValue"] = "server",
  ["MinScaledValue"] = "server",
  ["MaxScaledValue"] = "server",
  ["ScaledTolerance"] = "server",
  ["Scale"] = "server",
  ["AcceptedCommandList"] = "server",
  ["EventList"] = "server",
  ["AttributeList"] = "server",
}


-- Command Mapping
PressureMeasurement.command_direction_map = {
}


PressureMeasurement.FeatureMap = PressureMeasurement.types.Feature

function PressureMeasurement.are_features_supported(feature, feature_map)
  if (PressureMeasurement.FeatureMap.bits_are_valid(feature)) then
    return (feature & feature_map) == feature
  end
  return false
end

-- Cluster Completion
local attribute_helper_mt = {}
attribute_helper_mt.__index = function(self, key)
  local direction = PressureMeasurement.attribute_direction_map[key]
  if direction == nil then
    error(string.format("Referenced unknown attribute %s on cluster %s", key, PressureMeasurement.NAME))
  end
  return PressureMeasurement[direction].attributes[key]
end
PressureMeasurement.attributes = {}
setmetatable(PressureMeasurement.attributes, attribute_helper_mt)

local command_helper_mt = {}
command_helper_mt.__index = function(self, key)
  local direction = PressureMeasurement.command_direction_map[key]
  if direction == nil then
    error(string.format("Referenced unknown command %s on cluster %s", key, PressureMeasurement.NAME))
  end
  return PressureMeasurement[direction].commands[key]
end
PressureMeasurement.commands = {}
setmetatable(PressureMeasurement.commands, command_helper_mt)

local event_helper_mt = {}
event_helper_mt.__index = function(self, key)
  return PressureMeasurement.server.events[key]
end
PressureMeasurement.events = {}
setmetatable(PressureMeasurement.events, event_helper_mt)

setmetatable(PressureMeasurement, {__index = cluster_base})

return PressureMeasurement

