-- Copyright 2022 SmartThings
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- DO NOT EDIT: this code is automatically generated by ZCL Advanced Platform generator.

local data_types = require "st.matter.data_types"
local UintABC = require "st.matter.data_types.base_defs.UintABC"

--- @class st.matter.clusters.ServiceArea.types.SelectAreasStatus: st.matter.data_types.Uint8
--- @alias SelectAreasStatus
---
--- @field public byte_length number 1
--- @field public SUCCESS number 0
--- @field public UNSUPPORTED_AREA number 1
--- @field public INVALID_IN_MODE number 2
--- @field public INVALID_SET number 3

local SelectAreasStatus = {}
local new_mt = UintABC.new_mt({NAME = "SelectAreasStatus", ID = data_types.name_to_id_map["Uint8"]}, 1)
new_mt.__index.pretty_print = function(self)
  local name_lookup = {
    [self.SUCCESS] = "SUCCESS",
    [self.UNSUPPORTED_AREA] = "UNSUPPORTED_AREA",
    [self.INVALID_IN_MODE] = "INVALID_IN_MODE",
    [self.INVALID_SET] = "INVALID_SET",
  }
  return string.format("%s: %s", self.field_name or self.NAME, name_lookup[self.value] or string.format("%d", self.value))
end
new_mt.__tostring = new_mt.__index.pretty_print

new_mt.__index.SUCCESS  = 0x00
new_mt.__index.UNSUPPORTED_AREA  = 0x01
new_mt.__index.INVALID_IN_MODE  = 0x02
new_mt.__index.INVALID_SET  = 0x03

SelectAreasStatus.SUCCESS  = 0x00
SelectAreasStatus.UNSUPPORTED_AREA  = 0x01
SelectAreasStatus.INVALID_IN_MODE  = 0x02
SelectAreasStatus.INVALID_SET  = 0x03

SelectAreasStatus.augment_type = function(cls, val)
  setmetatable(val, new_mt)
end

setmetatable(SelectAreasStatus, new_mt)

return SelectAreasStatus

