-- Copyright 2022 SmartThings
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- DO NOT EDIT: this code is automatically generated by ZCL Advanced Platform generator.

local command_mt = {}
command_mt.__command_cache = {}
command_mt.__index = function(self, key)
  if command_mt.__command_cache[key] == nil then
    local req_loc = string.format("st.matter.generated.zap_clusters.OnOff.server.commands.%s", key)
    local raw_def = require(req_loc)
    local cluster = rawget(self, "_cluster")
    command_mt.__command_cache[key] = raw_def:set_parent_cluster(cluster)
  end
  return command_mt.__command_cache[key]
end

--- @class st.matter.generated.zap_clusters.OnOffServerCommands
---
--- @field public Off st.matter.generated.zap_clusters.OnOff.Off
--- @field public On st.matter.generated.zap_clusters.OnOff.On
--- @field public Toggle st.matter.generated.zap_clusters.OnOff.Toggle
--- @field public OffWithEffect st.matter.generated.zap_clusters.OnOff.OffWithEffect
--- @field public OnWithRecallGlobalScene st.matter.generated.zap_clusters.OnOff.OnWithRecallGlobalScene
--- @field public OnWithTimedOff st.matter.generated.zap_clusters.OnOff.OnWithTimedOff
local OnOffServerCommands = {}

function OnOffServerCommands:set_parent_cluster(cluster)
  self._cluster = cluster
  return self
end

setmetatable(OnOffServerCommands, command_mt)

return OnOffServerCommands

