-- Copyright 2022 SmartThings
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- DO NOT EDIT: this code is automatically generated by ZCL Advanced Platform generator.

local data_types = require "st.matter.data_types"
local UintABC = require "st.matter.data_types.base_defs.UintABC"

--- @class st.matter.clusters.OperationalState.types.ErrorStateEnum: st.matter.data_types.Uint8
--- @alias ErrorStateEnum
---
--- @field public byte_length number 1
--- @field public NO_ERROR number 0
--- @field public UNABLE_TO_START_OR_RESUME number 1
--- @field public UNABLE_TO_COMPLETE_OPERATION number 2
--- @field public COMMAND_INVALID_IN_STATE number 3

local ErrorStateEnum = {}
local new_mt = UintABC.new_mt({NAME = "ErrorStateEnum", ID = data_types.name_to_id_map["Uint8"]}, 1)
new_mt.__index.pretty_print = function(self)
  local name_lookup = {
    [self.NO_ERROR] = "NO_ERROR",
    [self.UNABLE_TO_START_OR_RESUME] = "UNABLE_TO_START_OR_RESUME",
    [self.UNABLE_TO_COMPLETE_OPERATION] = "UNABLE_TO_COMPLETE_OPERATION",
    [self.COMMAND_INVALID_IN_STATE] = "COMMAND_INVALID_IN_STATE",
  }
  return string.format("%s: %s", self.field_name or self.NAME, name_lookup[self.value] or string.format("%d", self.value))
end
new_mt.__tostring = new_mt.__index.pretty_print

new_mt.__index.NO_ERROR  = 0x00
new_mt.__index.UNABLE_TO_START_OR_RESUME  = 0x01
new_mt.__index.UNABLE_TO_COMPLETE_OPERATION  = 0x02
new_mt.__index.COMMAND_INVALID_IN_STATE  = 0x03

ErrorStateEnum.NO_ERROR  = 0x00
ErrorStateEnum.UNABLE_TO_START_OR_RESUME  = 0x01
ErrorStateEnum.UNABLE_TO_COMPLETE_OPERATION  = 0x02
ErrorStateEnum.COMMAND_INVALID_IN_STATE  = 0x03

ErrorStateEnum.augment_type = function(cls, val)
  setmetatable(val, new_mt)
end

setmetatable(ErrorStateEnum, new_mt)

return ErrorStateEnum

