name: 'Zigbee Switch Optimized'
packageKey: 'zigbee-switch-opt'
permissions:
  zigbee: {}
description: "SmartThings driver for Zigbee switch devices"
vendorSupportInformation: "https://support.smartthings.com"
