-- Copyright 2022 SmartThings, Inc.
-- Licensed under the Apache License, Version 2.0


-- DO NOT EDIT: this code is automatically generated by ZCL Advanced Platform generator.

local attr_mt = {}
attr_mt.__attr_cache = {}
attr_mt.__index = function(self, key)
  if attr_mt.__attr_cache[key] == nil then
    local req_loc = string.format("embedded_clusters.PressureMeasurement.server.attributes.%s", key)
    local raw_def = require(req_loc)
    local cluster = rawget(self, "_cluster")
    raw_def:set_parent_cluster(cluster)
    attr_mt.__attr_cache[key] = raw_def
  end
  return attr_mt.__attr_cache[key]
end

--- @class PressureMeasurementServerAttributes
---
--- @field public MeasuredValue PressureMeasurement.server.attributes.MeasuredValue
--- @field public MinMeasuredValue PressureMeasurement.server.attributes.MinMeasuredValue
--- @field public MaxMeasuredValue PressureMeasurement.server.attributes.MaxMeasuredValue
--- @field public Tolerance PressureMeasurement.server.attributes.Tolerance
--- @field public ScaledValue PressureMeasurement.server.attributes.ScaledValue
--- @field public MinScaledValue PressureMeasurement.server.attributes.MinScaledValue
--- @field public MaxScaledValue PressureMeasurement.server.attributes.MaxScaledValue
--- @field public ScaledTolerance PressureMeasurement.server.attributes.ScaledTolerance
--- @field public Scale PressureMeasurement.server.attributes.Scale
--- @field public AcceptedCommandList PressureMeasurement.server.attributes.AcceptedCommandList
--- @field public EventList PressureMeasurement.server.attributes.EventList
--- @field public AttributeList PressureMeasurement.server.attributes.AttributeList
local PressureMeasurementServerAttributes = {}

function PressureMeasurementServerAttributes:set_parent_cluster(cluster)
  self._cluster = cluster
  return self
end

setmetatable(PressureMeasurementServerAttributes, attr_mt)

return PressureMeasurementServerAttributes
