name: 'Z-Wave Mouse Trap'
packageKey: 'zwave-mouse-trap'
permissions:
  zwave: {}
description: "SmartThings driver for Z-Wave mouse trap devices"
vendorSupportInformation: "https://support.smartthings.com"
