-- Copyright 2022 SmartThings
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- DO NOT EDIT: this code is automatically generated by ZCL Advanced Platform generator.

local data_types = require "st.matter.data_types"
local UintABC = require "st.matter.data_types.base_defs.UintABC"

--- @class st.matter.clusters.OnOff.types.OnOffControl
--- @alias OnOffControl
---
--- @field public ACCEPT_ONLY_WHEN_ON number 1

local OnOffControl = {}
local new_mt = UintABC.new_mt({NAME = "OnOffControl", ID = data_types.name_to_id_map["Uint8"]}, 1)

OnOffControl.BASE_MASK = 0xFFFF
OnOffControl.ACCEPT_ONLY_WHEN_ON = 0x0001

OnOffControl.mask_fields = {
  BASE_MASK = 0xFFFF,
  ACCEPT_ONLY_WHEN_ON = 0x0001,
}

--- @function OnOffControl:is_accept_only_when_on_set
--- @return boolean True if the value of ACCEPT_ONLY_WHEN_ON is non-zero
OnOffControl.is_accept_only_when_on_set = function(self)
  return (self.value & self.ACCEPT_ONLY_WHEN_ON) ~= 0
end
 
--- @function OnOffControl:set_accept_only_when_on
--- Set the value of the bit in the ACCEPT_ONLY_WHEN_ON field to 1
OnOffControl.set_accept_only_when_on = function(self)
  if self.value ~= nil then
    self.value = self.value | self.ACCEPT_ONLY_WHEN_ON
  else
    self.value = self.ACCEPT_ONLY_WHEN_ON
  end
end

--- @function OnOffControl:unset_accept_only_when_on
--- Set the value of the bits in the ACCEPT_ONLY_WHEN_ON field to 0
OnOffControl.unset_accept_only_when_on = function(self)
  self.value = self.value & (~self.ACCEPT_ONLY_WHEN_ON & self.BASE_MASK)
end


OnOffControl.mask_methods = {
  is_accept_only_when_on_set = OnOffControl.is_accept_only_when_on_set,
  set_accept_only_when_on = OnOffControl.set_accept_only_when_on,
  unset_accept_only_when_on = OnOffControl.unset_accept_only_when_on,
}

OnOffControl.augment_type = function(cls, val)
  setmetatable(val, new_mt)
end

setmetatable(OnOffControl, new_mt)

return OnOffControl

