-- Copyright 2022 SmartThings
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- DO NOT EDIT: this code is automatically generated by ZCL Advanced Platform generator.

local data_types = require "st.matter.data_types"
local UintABC = require "st.matter.data_types.base_defs.UintABC"

--- @class st.matter.clusters.DiscoBall.types.RotateEnum: st.matter.data_types.Uint8
--- @alias RotateEnum
---
--- @field public byte_length number 1
--- @field public CLOCKWISE number 1
--- @field public COUNTER_CLOCKWISE number 2

local RotateEnum = {}
local new_mt = UintABC.new_mt({NAME = "RotateEnum", ID = data_types.name_to_id_map["Uint8"]}, 1)
new_mt.__index.pretty_print = function(self)
  local name_lookup = {
    [self.CLOCKWISE] = "CLOCKWISE",
    [self.COUNTER_CLOCKWISE] = "COUNTER_CLOCKWISE",
  }
  return string.format("%s: %s", self.field_name or self.NAME, name_lookup[self.value] or string.format("%d", self.value))
end
new_mt.__tostring = new_mt.__index.pretty_print

new_mt.__index.CLOCKWISE  = 0x01
new_mt.__index.COUNTER_CLOCKWISE  = 0x02

RotateEnum.CLOCKWISE  = 0x01
RotateEnum.COUNTER_CLOCKWISE  = 0x02

RotateEnum.augment_type = function(cls, val)
  setmetatable(val, new_mt)
end

setmetatable(RotateEnum, new_mt)

local status, aliases = pcall(require, "st.matter.clusters.aliases.DiscoBall.types.RotateEnum")
if status then
  for key, alias in pairs(aliases) do
    new_mt.__index[key] = new_mt.__index[alias]
  end
end

return RotateEnum

