-- Copyright 2022 SmartThings
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- DO NOT EDIT: this code is automatically generated by ZCL Advanced Platform generator.

local data_types = require "st.matter.data_types"
local UintABC = require "st.matter.data_types.base_defs.UintABC"

--- @class st.matter.clusters.OnOff.types.SceneFeatures
--- @alias SceneFeatures
---
--- @field public SCENE_NAMES number 1

local SceneFeatures = {}
local new_mt = UintABC.new_mt({NAME = "SceneFeatures", ID = data_types.name_to_id_map["Uint32"]}, 4)

SceneFeatures.BASE_MASK = 0xFFFF
SceneFeatures.SCENE_NAMES = 0x0001

SceneFeatures.mask_fields = {
  BASE_MASK = 0xFFFF,
  SCENE_NAMES = 0x0001,
}

--- @function SceneFeatures:is_scene_names_set
--- @return boolean True if the value of SCENE_NAMES is non-zero
SceneFeatures.is_scene_names_set = function(self)
  return (self.value & self.SCENE_NAMES) ~= 0
end
 
--- @function SceneFeatures:set_scene_names
--- Set the value of the bit in the SCENE_NAMES field to 1
SceneFeatures.set_scene_names = function(self)
  if self.value ~= nil then
    self.value = self.value | self.SCENE_NAMES
  else
    self.value = self.SCENE_NAMES
  end
end

--- @function SceneFeatures:unset_scene_names
--- Set the value of the bits in the SCENE_NAMES field to 0
SceneFeatures.unset_scene_names = function(self)
  self.value = self.value & (~self.SCENE_NAMES & self.BASE_MASK)
end


SceneFeatures.mask_methods = {
  is_scene_names_set = SceneFeatures.is_scene_names_set,
  set_scene_names = SceneFeatures.set_scene_names,
  unset_scene_names = SceneFeatures.unset_scene_names,
}

SceneFeatures.augment_type = function(cls, val)
  setmetatable(val, new_mt)
end

setmetatable(SceneFeatures, new_mt)

return SceneFeatures

