-- Copyright 2022 SmartThings
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- DO NOT EDIT: this code is automatically generated by ZCL Advanced Platform generator.

local data_types = require "st.matter.data_types"
local UintABC = require "st.matter.data_types.base_defs.UintABC"

--- @class st.matter.clusters.DiscoBall.types.WobbleBitmap
--- @alias WobbleBitmap
---
--- @field public WOBBLE_LEFT_RIGHT number 1
--- @field public WOBBLE_UP_DOWN number 2
--- @field public WOBBLE_ROUND number 4

local WobbleBitmap = {}
local new_mt = UintABC.new_mt({NAME = "WobbleBitmap", ID = data_types.name_to_id_map["Uint8"]}, 1)

WobbleBitmap.BASE_MASK = 0xFFFF
WobbleBitmap.WOBBLE_LEFT_RIGHT = 0x0001
WobbleBitmap.WOBBLE_UP_DOWN = 0x0002
WobbleBitmap.WOBBLE_ROUND = 0x0004

WobbleBitmap.mask_fields = {
  BASE_MASK = 0xFFFF,
  WOBBLE_LEFT_RIGHT = 0x0001,
  WOBBLE_UP_DOWN = 0x0002,
  WOBBLE_ROUND = 0x0004,
}

--- @function WobbleBitmap:is_wobble_left_right_set
--- @return boolean True if the value of WOBBLE_LEFT_RIGHT is non-zero
WobbleBitmap.is_wobble_left_right_set = function(self)
  return (self.value & self.WOBBLE_LEFT_RIGHT) ~= 0
end

--- @function WobbleBitmap:set_wobble_left_right
--- Set the value of the bit in the WOBBLE_LEFT_RIGHT field to 1
WobbleBitmap.set_wobble_left_right = function(self)
  if self.value ~= nil then
    self.value = self.value | self.WOBBLE_LEFT_RIGHT
  else
    self.value = self.WOBBLE_LEFT_RIGHT
  end
end

--- @function WobbleBitmap:unset_wobble_left_right
--- Set the value of the bits in the WOBBLE_LEFT_RIGHT field to 0
WobbleBitmap.unset_wobble_left_right = function(self)
  self.value = self.value & (~self.WOBBLE_LEFT_RIGHT & self.BASE_MASK)
end
--- @function WobbleBitmap:is_wobble_up_down_set
--- @return boolean True if the value of WOBBLE_UP_DOWN is non-zero
WobbleBitmap.is_wobble_up_down_set = function(self)
  return (self.value & self.WOBBLE_UP_DOWN) ~= 0
end

--- @function WobbleBitmap:set_wobble_up_down
--- Set the value of the bit in the WOBBLE_UP_DOWN field to 1
WobbleBitmap.set_wobble_up_down = function(self)
  if self.value ~= nil then
    self.value = self.value | self.WOBBLE_UP_DOWN
  else
    self.value = self.WOBBLE_UP_DOWN
  end
end

--- @function WobbleBitmap:unset_wobble_up_down
--- Set the value of the bits in the WOBBLE_UP_DOWN field to 0
WobbleBitmap.unset_wobble_up_down = function(self)
  self.value = self.value & (~self.WOBBLE_UP_DOWN & self.BASE_MASK)
end
--- @function WobbleBitmap:is_wobble_round_set
--- @return boolean True if the value of WOBBLE_ROUND is non-zero
WobbleBitmap.is_wobble_round_set = function(self)
  return (self.value & self.WOBBLE_ROUND) ~= 0
end

--- @function WobbleBitmap:set_wobble_round
--- Set the value of the bit in the WOBBLE_ROUND field to 1
WobbleBitmap.set_wobble_round = function(self)
  if self.value ~= nil then
    self.value = self.value | self.WOBBLE_ROUND
  else
    self.value = self.WOBBLE_ROUND
  end
end

--- @function WobbleBitmap:unset_wobble_round
--- Set the value of the bits in the WOBBLE_ROUND field to 0
WobbleBitmap.unset_wobble_round = function(self)
  self.value = self.value & (~self.WOBBLE_ROUND & self.BASE_MASK)
end


WobbleBitmap.mask_methods = {
  is_wobble_left_right_set = WobbleBitmap.is_wobble_left_right_set,
  set_wobble_left_right = WobbleBitmap.set_wobble_left_right,
  unset_wobble_left_right = WobbleBitmap.unset_wobble_left_right,
  is_wobble_up_down_set = WobbleBitmap.is_wobble_up_down_set,
  set_wobble_up_down = WobbleBitmap.set_wobble_up_down,
  unset_wobble_up_down = WobbleBitmap.unset_wobble_up_down,
  is_wobble_round_set = WobbleBitmap.is_wobble_round_set,
  set_wobble_round = WobbleBitmap.set_wobble_round,
  unset_wobble_round = WobbleBitmap.unset_wobble_round,
}

WobbleBitmap.augment_type = function(cls, val)
  setmetatable(val, new_mt)
end

setmetatable(WobbleBitmap, new_mt)

return WobbleBitmap

