-- Copyright 2022 SmartThings
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- DO NOT EDIT: this code is automatically generated by ZCL Advanced Platform generator.

local data_types = require "st.matter.data_types"
local UintABC = require "st.matter.data_types.base_defs.UintABC"

--- @class st.matter.clusters.OperationalState.types.OperationalStateEnum: st.matter.data_types.Uint8
--- @alias OperationalStateEnum
---
--- @field public byte_length number 1
--- @field public SEEKING_CHARGER number 64
--- @field public CHARGING number 65
--- @field public DOCKED number 66

local OperationalStateEnum = {}
local new_mt = UintABC.new_mt({NAME = "OperationalStateEnum", ID = data_types.name_to_id_map["Uint8"]}, 1)
new_mt.__index.pretty_print = function(self)
  local name_lookup = {
    [self.SEEKING_CHARGER] = "SEEKING_CHARGER",
    [self.CHARGING] = "CHARGING",
    [self.DOCKED] = "DOCKED",
  }
  return string.format("%s: %s", self.field_name or self.NAME, name_lookup[self.value] or string.format("%d", self.value))
end
new_mt.__tostring = new_mt.__index.pretty_print

new_mt.__index.SEEKING_CHARGER  = 0x40
new_mt.__index.CHARGING  = 0x41
new_mt.__index.DOCKED  = 0x42

OperationalStateEnum.SEEKING_CHARGER  = 0x40
OperationalStateEnum.CHARGING  = 0x41
OperationalStateEnum.DOCKED  = 0x42

OperationalStateEnum.augment_type = function(cls, val)
  setmetatable(val, new_mt)
end

setmetatable(OperationalStateEnum, new_mt)

return OperationalStateEnum

