-- Copyright 2022 SmartThings
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- DO NOT EDIT: this code is automatically generated by ZCL Advanced Platform generator.

local cluster_base = require "st.matter.cluster_base"
local RvcRunModeServerAttributes = require "RvcRunMode.server.attributes"
local RvcRunModeServerCommands = require "RvcRunMode.server.commands"
local RvcRunModeClientCommands = require "RvcRunMode.client.commands"
local RvcRunModeTypes = require "RvcRunMode.types"

--- @class RvcRunMode
--- @alias RvcRunMode
---
--- @field public ID number 0x0054 the ID of this cluster
--- @field public NAME string "RvcRunMode" the name of this cluster
--- @field public attributes RvcRunModeServerAttributes | RvcRunModeClientAttributes
--- @field public commands RvcRunModeServerCommands | RvcRunModeClientCommands
--- @field public types RvcRunModeTypes

local RvcRunMode = {}

RvcRunMode.ID = 0x0054
RvcRunMode.NAME = "RvcRunMode"
RvcRunMode.server = {}
RvcRunMode.client = {}
RvcRunMode.server.attributes = RvcRunModeServerAttributes:set_parent_cluster(RvcRunMode)
RvcRunMode.server.commands = RvcRunModeServerCommands:set_parent_cluster(RvcRunMode)
RvcRunMode.client.commands = RvcRunModeClientCommands:set_parent_cluster(RvcRunMode)
RvcRunMode.types = RvcRunModeTypes

--- Find an attribute by id
---
--- @param attr_id number
function RvcRunMode:get_attribute_by_id(attr_id)
  local attr_id_map = {
    [0x0000] = "SupportedModes",
    [0x0001] = "CurrentMode",
    [0x0002] = "StartUpMode",
    [0x0003] = "OnMode",
    [0xFFF9] = "AcceptedCommandList",
    [0xFFFA] = "EventList",
    [0xFFFB] = "AttributeList",
  }
  local attr_name = attr_id_map[attr_id]
  if attr_name ~= nil then
    return self.attributes[attr_name]
  end
  return nil
end

--- Find a server command by id
---
--- @param command_id number
function RvcRunMode:get_server_command_by_id(command_id)
  local server_id_map = {
    [0x0000] = "ChangeToMode",
  }
  if server_id_map[command_id] ~= nil then
    return self.server.commands[server_id_map[command_id]]
  end
  return nil
end

function RvcRunMode:get_client_command_by_id(command_id)
  local client_id_map = {
    [0x0001] = "ChangeToModeResponse",
  }
  if client_id_map[command_id] ~= nil then
    return self.client.commands[client_id_map[command_id]]
  end
  return nil
end

-- Attribute Mapping
RvcRunMode.attribute_direction_map = {
  ["SupportedModes"] = "server",
  ["CurrentMode"] = "server",
  ["StartUpMode"] = "server",
  ["OnMode"] = "server",
  ["AcceptedCommandList"] = "server",
  ["EventList"] = "server",
  ["AttributeList"] = "server",
}

do
  local has_aliases, aliases = pcall(require, "st.matter.clusters.aliases.RvcRunMode.server.attributes")
  if has_aliases then
    for alias, _ in pairs(aliases) do
      RvcRunMode.attribute_direction_map[alias] = "server"
    end
  end
end

-- Command Mapping
RvcRunMode.command_direction_map = {
  ["ChangeToMode"] = "server",
  ["ChangeToModeResponse"] = "client",
}

do
  local has_aliases, aliases = pcall(require, "st.matter.clusters.aliases.RvcRunMode.server.commands")
  if has_aliases then
    for alias, _ in pairs(aliases) do
      RvcRunMode.command_direction_map[alias] = "server"
    end
  end
end

do
  local has_aliases, aliases = pcall(require, "st.matter.clusters.aliases.RvcRunMode.client.commands")
  if has_aliases then
    for alias, _ in pairs(aliases) do
      RvcRunMode.command_direction_map[alias] = "client"
    end
  end
end

RvcRunMode.FeatureMap = RvcRunMode.types.Feature

function RvcRunMode.are_features_supported(feature, feature_map)
  if (RvcRunMode.FeatureMap.bits_are_valid(feature)) then
    return (feature & feature_map) == feature
  end
  return false
end

-- Cluster Completion
local attribute_helper_mt = {}
attribute_helper_mt.__index = function(self, key)
  local direction = RvcRunMode.attribute_direction_map[key]
  if direction == nil then
    error(string.format("Referenced unknown attribute %s on cluster %s", key, RvcRunMode.NAME))
  end
  return RvcRunMode[direction].attributes[key]
end
RvcRunMode.attributes = {}
setmetatable(RvcRunMode.attributes, attribute_helper_mt)

local command_helper_mt = {}
command_helper_mt.__index = function(self, key)
  local direction = RvcRunMode.command_direction_map[key]
  if direction == nil then
    error(string.format("Referenced unknown command %s on cluster %s", key, RvcRunMode.NAME))
  end
  return RvcRunMode[direction].commands[key]
end
RvcRunMode.commands = {}
setmetatable(RvcRunMode.commands, command_helper_mt)

setmetatable(RvcRunMode, {__index = cluster_base})

return RvcRunMode

