name: 'Zigbee Dimmer Remote'
packageKey: 'zigbee-dimmer-remote'
permissions:
  zigbee: {}
description: "SmartThings driver for Zigbee dimmer remote devices"
vendorSupportInformation: "https://support.smartthings.com"
