name: 'Aqara Lock'
packageKey: 'aqara-lock'
permissions:
  zigbee: {}
  aqara-provisioning: {}
description: "SmartThings driver for Aqara Doorlock"
vendorSupportInformation: "https://www.aqara.com/en/support/"
