-- Copyright 2025 SmartThings, Inc.
-- Licensed under the Apache License, Version 2.0

return {
  { mfr = "DAWON_DNS", model = "PM-S240-ZB", children = 1 },
  { mfr = "DAWON_DNS", model = "PM-S240R-ZB", children = 1 },
  { mfr = "DAWON_DNS", model = "PM-S250-ZB", children = 1 },
  { mfr = "DAWON_DNS", model = "PM-S340-ZB", children = 2 },
  { mfr = "DAWON_DNS", model = "PM-S340R-ZB", children = 2 },
  { mfr = "DAWON_DNS", model = "PM-S350-ZB", children = 2 },
  { mfr = "DAWON_DNS", model = "ST-S250-ZB", children = 1 },
  { mfr = "DAWON_DNS", model = "ST-S350-ZB", children = 2 },
  { mfr = "ORVIBO", model = "074b3ffba5a045b7afd94c47079dd553", children = 1 },
  { mfr = "ORVIBO", model = "9f76c9f31b4c4a499e3aca0977ac4494", children = 2 },
  { mfr = "REXENSE", model = "HY0002", children = 1 },
  { mfr = "REXENSE", model = "HY0003", children = 2 },
  { mfr = "REX", model = "HY0096", children = 1 },
  { mfr = "REX", model = "HY0097", children = 2 },
  { mfr = "HEIMAN", model = "HS2SW2L-EFR-3.0", children = 1 },
  { mfr = "HEIMAN", model = "HS2SW3L-EFR-3.0", children = 2 },
  { mfr = "HEIMAN", model = "HS6SW2A-W-EF-3.0", children = 1 },
  { mfr = "HEIMAN", model = "HS6SW3A-W-EF-3.0", children = 2 },
  { mfr = "eWeLink", model = "ZB-SW02", children = 1 },
  { mfr = "eWeLink", model = "ZB-SW03", children = 2 },
  { mfr = "eWeLink", model = "ZB-SW04", children = 3 },
  { mfr = "SMARTvill", model = "SLA01", children = 0 },
  { mfr = "SMARTvill", model = "SLA02", children = 1 },
  { mfr = "SMARTvill", model = "SLA03", children = 2 },
  { mfr = "SMARTvill", model = "SLA04", children = 3 },
  { mfr = "SMARTvill", model = "SLA05", children = 4 },
  { mfr = "SMARTvill", model = "SLA06", children = 5 },
  { mfr = "ShinaSystem", model = "SBM300Z2", children = 1 },
  { mfr = "ShinaSystem", model = "SBM300Z3", children = 2 },
  { mfr = "ShinaSystem", model = "SBM300Z4", children = 3 },
  { mfr = "ShinaSystem", model = "SBM300Z5", children = 4 },
  { mfr = "ShinaSystem", model = "SBM300Z6", children = 5 },
  { mfr = "ShinaSystem", model = "SQM300Z2", children = 1 },
  { mfr = "ShinaSystem", model = "SQM300Z3", children = 2 },
  { mfr = "ShinaSystem", model = "SQM300Z4", children = 3 },
  { mfr = "ShinaSystem", model = "SQM300Z6", children = 5 },
  { model = "E220-KR2N0Z0-HA", children = 1 },
  { model = "E220-KR3N0Z0-HA", children = 2 },
  { model = "E220-KR4N0Z0-HA", children = 3 },
  { model = "E220-KR5N0Z0-HA", children = 4 },
  { model = "E220-KR6N0Z0-HA", children = 5 }
}
