-- Copyright 2022 SmartThings
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- DO NOT EDIT: this code is automatically generated by ZCL Advanced Platform generator.

local attr_mt = {}
attr_mt.__attr_cache = {}
attr_mt.__index = function(self, key)
  if attr_mt.__attr_cache[key] == nil then
    local req_loc = string.format("st.matter.generated.zap_clusters.OnOff.server.attributes.%s", key)
    local raw_def = require(req_loc)
    local cluster = rawget(self, "_cluster")
    raw_def:set_parent_cluster(cluster)
    attr_mt.__attr_cache[key] = raw_def
  end
  return attr_mt.__attr_cache[key]
end

--- @class st.matter.generated.zap_clusters.OnOffServerAttributes
---
--- @field public OnOff st.matter.generated.zap_clusters.OnOff.server.attributes.OnOff
--- @field public GlobalSceneControl st.matter.generated.zap_clusters.OnOff.server.attributes.GlobalSceneControl
--- @field public OnTime st.matter.generated.zap_clusters.OnOff.server.attributes.OnTime
--- @field public OffWaitTime st.matter.generated.zap_clusters.OnOff.server.attributes.OffWaitTime
--- @field public StartUpOnOff st.matter.generated.zap_clusters.OnOff.server.attributes.StartUpOnOff
--- @field public AcceptedCommandList st.matter.generated.zap_clusters.OnOff.server.attributes.AcceptedCommandList
--- @field public AttributeList st.matter.generated.zap_clusters.OnOff.server.attributes.AttributeList
local OnOffServerAttributes = {}

function OnOffServerAttributes:set_parent_cluster(cluster)
  self._cluster = cluster
  return self
end

setmetatable(OnOffServerAttributes, attr_mt)

return OnOffServerAttributes

