-- Copyright 2022 SmartThings
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- DO NOT EDIT: this code is automatically generated by ZCL Advanced Platform generator.

local cluster_base = require "st.matter.cluster_base"
local ServiceAreaServerAttributes = require "ServiceArea.server.attributes"
local ServiceAreaServerCommands = require "ServiceArea.server.commands"
local ServiceAreaClientCommands = require "ServiceArea.client.commands"
local ServiceAreaTypes = require "ServiceArea.types"

--- @class ServiceArea
--- @alias ServiceArea
---
--- @field public ID number 0x0150 the ID of this cluster
--- @field public NAME string "ServiceArea" the name of this cluster
--- @field public attributes ServiceAreaServerAttributes | ServiceAreaClientAttributes
--- @field public commands ServiceAreaServerCommands | ServiceAreaClientCommands
--- @field public types ServiceAreaTypes

local ServiceArea = {}

ServiceArea.ID = 0x0150
ServiceArea.NAME = "ServiceArea"
ServiceArea.server = {}
ServiceArea.client = {}
ServiceArea.server.attributes = ServiceAreaServerAttributes:set_parent_cluster(ServiceArea)
ServiceArea.server.commands = ServiceAreaServerCommands:set_parent_cluster(ServiceArea)
ServiceArea.client.commands = ServiceAreaClientCommands:set_parent_cluster(ServiceArea)
ServiceArea.types = ServiceAreaTypes

--- Find an attribute by id
---
--- @param attr_id number
function ServiceArea:get_attribute_by_id(attr_id)
  local attr_id_map = {
    [0x0000] = "SupportedAreas",
    [0x0001] = "SupportedMaps",
    [0x0002] = "SelectedAreas",
    [0x0003] = "CurrentArea",
    [0x0004] = "EstimatedEndTime",
    [0x0005] = "Progress",
    [0xFFF9] = "AcceptedCommandList",
    [0xFFFA] = "EventList",
    [0xFFFB] = "AttributeList",
  }
  local attr_name = attr_id_map[attr_id]
  if attr_name ~= nil then
    return self.attributes[attr_name]
  end
  return nil
end

--- Find a server command by id
---
--- @param command_id number
function ServiceArea:get_server_command_by_id(command_id)
  local server_id_map = {
    [0x0000] = "SelectAreas",
    [0x0002] = "SkipArea",
  }
  if server_id_map[command_id] ~= nil then
    return self.server.commands[server_id_map[command_id]]
  end
  return nil
end

--- Find a client command by id
---
--- @param command_id number
function ServiceArea:get_client_command_by_id(command_id)
  local client_id_map = {
    [0x0001] = "SelectAreasResponse",
    [0x0003] = "SkipAreaResponse",
  }
  if client_id_map[command_id] ~= nil then
    return self.client.commands[client_id_map[command_id]]
  end
  return nil
end

-- Attribute Mapping
ServiceArea.attribute_direction_map = {
  ["SupportedAreas"] = "server",
  ["SupportedMaps"] = "server",
  ["SelectedAreas"] = "server",
  ["CurrentArea"] = "server",
  ["EstimatedEndTime"] = "server",
  ["Progress"] = "server",
  ["AcceptedCommandList"] = "server",
  ["EventList"] = "server",
  ["AttributeList"] = "server",
}

do
  local has_aliases, aliases = pcall(require, "aliases.ServiceArea.server.attributes")
  if has_aliases then
    for alias, _ in pairs(aliases) do
      ServiceArea.attribute_direction_map[alias] = "server"
    end
  end
end

-- Command Mapping
ServiceArea.command_direction_map = {
  ["SelectAreas"] = "server",
  ["SkipArea"] = "server",
  ["SelectAreasResponse"] = "client",
  ["SkipAreaResponse"] = "client",
}

do
  local has_aliases, aliases = pcall(require, "st.matter.clusters.aliases.ServiceArea.server.commands")
  if has_aliases then
    for alias, _ in pairs(aliases) do
      ServiceArea.command_direction_map[alias] = "server"
    end
  end
end

do
  local has_aliases, aliases = pcall(require, "st.matter.clusters.aliases.ServiceArea.client.commands")
  if has_aliases then
    for alias, _ in pairs(aliases) do
      ServiceArea.command_direction_map[alias] = "client"
    end
  end
end

ServiceArea.FeatureMap = ServiceArea.types.Feature

function ServiceArea.are_features_supported(feature, feature_map)
  if (ServiceArea.FeatureMap.bits_are_valid(feature)) then
    return (feature & feature_map) == feature
  end
  return false
end

-- Cluster Completion
local attribute_helper_mt = {}
attribute_helper_mt.__index = function(self, key)
  local direction = ServiceArea.attribute_direction_map[key]
  if direction == nil then
    error(string.format("Referenced unknown attribute %s on cluster %s", key, ServiceArea.NAME))
  end
  return ServiceArea[direction].attributes[key]
end
ServiceArea.attributes = {}
setmetatable(ServiceArea.attributes, attribute_helper_mt)

local command_helper_mt = {}
command_helper_mt.__index = function(self, key)
  local direction = ServiceArea.command_direction_map[key]
  if direction == nil then
    error(string.format("Referenced unknown command %s on cluster %s", key, ServiceArea.NAME))
  end
  return ServiceArea[direction].commands[key]
end
ServiceArea.commands = {}
setmetatable(ServiceArea.commands, command_helper_mt)

local event_helper_mt = {}
event_helper_mt.__index = function(self, key)
  return ServiceArea.server.events[key]
end
ServiceArea.events = {}
setmetatable(ServiceArea.events, event_helper_mt)

setmetatable(ServiceArea, {__index = cluster_base})

return ServiceArea

