-- Copyright 2022 SmartThings, Inc.
-- Licensed under the Apache License, Version 2.0


-- DO NOT EDIT: this code is automatically generated by ZCL Advanced Platform generator.

local types_mt = {}
types_mt.__types_cache = {}
types_mt.__index = function(self, key)
  if types_mt.__types_cache[key] == nil then
    types_mt.__types_cache[key] = require("embedded_clusters.PressureMeasurement.types." .. key)
  end
  return types_mt.__types_cache[key]
end

--- @class PressureMeasurementTypes
---

--- @field public Feature PressureMeasurement.types.Feature
local PressureMeasurementTypes = {}

setmetatable(PressureMeasurementTypes, types_mt)

return PressureMeasurementTypes
