#!/usr/bin/env bash
#
# Copyright 2025 SmartThings, Inc.
# Licensed under the Apache License, Version 2.0
#
# pre-commit
#
# - Copy to .git/hooks/pre-commit
# - Ensure executable

set -e

# Get changed files that are Added or Modified
files=$(git diff --staged --name-only --diff-filter=AM)

fail=0
for file in $files; do
    # Only process .lua files
    case "$file" in
        *.lua)
            # Skip if not a regular file
            [ -f "$file" ] || continue

            # Check if file is not empty, is a SmartThings driver and has the copyright header
            if [ -s "$file" ] && [[ "$file" =~ "drivers/SmartThings" ]] 
                && [[ ! $(grep $file -P -e "-{2,} Copyright \d{4}(?:-\d{4})? SmartThings") ]]; then
                echo "$file: SmartThings Copyright missing from file"
                fail=1
            fi

            # Check if file is non-empty and does NOT end with a newline
            if [ -s "$file" ] && [ -n "$(tail -c 1 "$file")" ]; then
                echo "$file: Missing newline at end of file"
                fail=1
            fi
            ;;
    esac
done

exit $fail
