name: Post duplicate profile comment
on:
  workflow_run:
    workflows: [Check for duplicate profiles]
    types:
      - completed

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Download comment artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: duplicate-profiles.yml
          run_id: ${{ github.event.workflow_run.id }}

      - run: echo "pr_number=$(cat pr_number/pr_number.txt)" >> $GITHUB_ENV

      - name: Find comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          body-includes: Duplicate profile check
          comment-author: 'github-actions[bot]'
          issue-number: ${{ env.pr_number }}

      - name: Post comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body-file: 'duplicate_profile_comment/profile-comment-body.md'
          edit-mode: replace
          issue-number: ${{ env.pr_number }}
