name: Luacheck
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'drivers/**'
jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v0
        with:
          args: --config .github/workflows/.luacheckrc .