name: Publish test results
on:
  workflow_run:
    workflows: [Run driver tests]
    types:
      - completed

jobs:
  publish-test-results:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: run-tests.yml
          run_id: ${{ github.event.workflow_run.id }}
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: event-file/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: "tests/*.xml"