name: Define test versions
on:
  workflow_call

jobs:
  define-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.set.outputs.versions }}
    steps:
      - id: set
        run: echo 'versions=["60","52"]' >> "GITHUB_OUTPUT"
